// <auto-generated />
using System;
using CitiesManager.Infrastructure.DatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CitiesManager.WebAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250131172900_CityNameRequired")]
    partial class CityNameRequired
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CitiesManager.WebAPI.Models.City", b =>
                {
                    b.Property<Guid>("CityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CityID");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            CityID = new Guid("4c3b926a-e4f2-4b8a-975e-450dc8c6a05a"),
                            CityName = "New York"
                        },
                        new
                        {
                            CityID = new Guid("bce7df34-6967-4ce3-bc7a-b93e46276851"),
                            CityName = "Los Angeles"
                        },
                        new
                        {
                            CityID = new Guid("a16b099c-6de8-4983-87ef-d23a3aade4dd"),
                            CityName = "Chicago"
                        },
                        new
                        {
                            CityID = new Guid("23a91d2d-6d76-4f5d-afbd-22f6f6e524d0"),
                            CityName = "Houston"
                        },
                        new
                        {
                            CityID = new Guid("de0fe150-bd1f-4532-a8d1-f069470d5467"),
                            CityName = "Phoenix"
                        },
                        new
                        {
                            CityID = new Guid("4f41ee7b-0b81-4892-8106-6dd848f87172"),
                            CityName = "Philadelphia"
                        },
                        new
                        {
                            CityID = new Guid("948ea9c6-5cc2-463e-a58e-b08387556fe9"),
                            CityName = "San Antonio"
                        },
                        new
                        {
                            CityID = new Guid("93c49eb2-47dd-47bd-b873-ea4aa9f18506"),
                            CityName = "San Diego"
                        },
                        new
                        {
                            CityID = new Guid("7bce0658-134d-45d3-92c6-d5851ceb5f71"),
                            CityName = "Dallas"
                        },
                        new
                        {
                            CityID = new Guid("199af6c4-3945-4038-b642-60402632afe9"),
                            CityName = "San Jose"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
