// <auto-generated />
using System;
using CitiesManager.WebAPI.DatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CitiesManager.WebAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CitiesManager.WebAPI.Models.City", b =>
                {
                    b.Property<Guid>("CityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CityName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CityID");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            CityID = new Guid("e1d798ff-2dd7-4e30-a95e-57c5b85d2b09"),
                            CityName = "New York"
                        },
                        new
                        {
                            CityID = new Guid("4bd0883f-7bb9-4be6-b77a-888c730313fb"),
                            CityName = "Los Angeles"
                        },
                        new
                        {
                            CityID = new Guid("417942f9-0522-4d1f-b986-18a1d5a732d9"),
                            CityName = "Chicago"
                        },
                        new
                        {
                            CityID = new Guid("270abbdd-3d39-442c-add2-6cb0523a109d"),
                            CityName = "Houston"
                        },
                        new
                        {
                            CityID = new Guid("be8b8228-13a7-4dfc-b1d9-2edaf32a1b06"),
                            CityName = "Phoenix"
                        },
                        new
                        {
                            CityID = new Guid("612ce742-88aa-4947-9c0e-c1fd90f098d5"),
                            CityName = "Philadelphia"
                        },
                        new
                        {
                            CityID = new Guid("d3676f25-23b4-456c-b12a-0341ed4416b3"),
                            CityName = "San Antonio"
                        },
                        new
                        {
                            CityID = new Guid("803f07dc-a072-4c4d-ad0a-da9c2e397575"),
                            CityName = "San Diego"
                        },
                        new
                        {
                            CityID = new Guid("1a672668-ef24-4a31-bd0f-2bcff92a3cca"),
                            CityName = "Dallas"
                        },
                        new
                        {
                            CityID = new Guid("3b66aa9d-c90b-4388-8304-0b53d84ec88b"),
                            CityName = "San Jose"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
